"""empty message

Revision ID: 160f48b216ef
Revises: 
Create Date: 2022-05-01 21:11:50.975652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160f48b216ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phonetic_symbol', sa.String(length=64), nullable=True),
    sa.Column('use_case', sa.String(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('STAGE1', 'STAGE2', 'STAGE3', 'STAGE4', 'STAGE5', name='reviewstage'), nullable=True),
    sa.Column('status', sa.Enum('UNREVIEWED', 'REVIEWED', 'REMEMBERED', 'UNREMEMBERED', name='reviewstatus'), nullable=True),
    sa.Column('review_plan_type', sa.Enum('HINT_WORD', 'HINT_MEANING', name='reviewplantype'), nullable=True),
    sa.Column('time_to_review', sa.DateTime(), nullable=True),
    sa.Column('reviewed_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meaning_id'], ['meaning.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_plan')
    op.drop_table('meaning')
    op.drop_table('word')
    op.drop_table('add_counter')
    # ### end Alembic commands ###
