"""empty message

Revision ID: 5d9547a5be02
Revises: 160f48b216ef
Create Date: 2022-05-29 16:06:55.222762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9547a5be02'
down_revision = '160f48b216ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('er_lookup_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meaning_id'], ['meaning.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('er_lookup_record')
    # ### end Alembic commands ###
