"""empty message

Revision ID: 22c07d35f197
Revises: 275b21a69463
Create Date: 2020-03-23 09:43:04.299844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c07d35f197'
down_revision = '275b21a69463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_plans', sa.Column('review_plan_type', sa.Enum('HINT_WORD', 'HINT_MEANING', name='reviewplantype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_plans', 'review_plan_type')
    # ### end Alembic commands ###
