"""empty message

Revision ID: bf0462c8c571
Revises: 
Create Date: 2019-08-11 17:25:46.480749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0462c8c571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('phonetic_symbol', sa.String(length=64), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('review_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('STAGE1', 'STAGE2', 'STAGE3', 'STAGE4', 'STAGE5', name='reviewstage'), nullable=True),
    sa.Column('status', sa.Enum('UNREVIEWED', 'REVIEWED', 'REMEMBERED', 'UNREMEMBERED', name='reviewstatus'), nullable=True),
    sa.Column('time_to_review', sa.DateTime(), nullable=True),
    sa.Column('reviewed_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('changed_time', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_plans')
    op.drop_table('words')
    # ### end Alembic commands ###
